### ISSUE TITLE
no confirmation when a payment is being done

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/galoy-pay#39] opened 2021-04-30 17:00 UTC
There is no automatic payment confirmation currently.

Step to reproduce:
- open https://ln.bitcoinbeach.com/nicolas
- pay one sats
- page doesn't refresh

**Comment by leesalminen** [comment] 2021-12-18 01:43
I just tried this and was unable to reproduce. Enjoy your sats, @nicolasburtey ;).

**Comment by krtk6160** [comment] 2021-12-18 07:30
> There is no automatic payment confirmation currently.
> 
> Step to reproduce:
> 
> * open https://ln.bitcoinbeach.com/nicolas
> * pay one sats
> * page doesn't refresh

Could you post log output from the browser console? I've been facing this issue as well on my laptop with brave browser, but with firefox it works perfectly. Are you also using brave by any chance?

My log output shows this error -> `WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.`

**Comment by nicolasburtey** [comment] 2021-12-18 08:00
I am using brave yes

**Comment by leesalminen** [comment] 2021-12-20 18:01
I tried this out using Brave `Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (arm64)` on MacOS 12.0.1 a couple times and was unable to reproduce. Initially I was testing with Safari 15.1 and Firefox 95.0 on the same machine. 

I did find some potentially related issues reported on other projects:

- https://github.com/brave/brave-browser/issues/15410
- https://github.com/hasura/graphql-engine/issues/4509

On https://github.com/hasura/graphql-engine/issues/4509 someone mentioned that adding `lazy: true` to the `new WebSocketLink()` `options` object fixed the issue for them.

On the whole though, this seems like an issue with Brave Browser with many different developers reporting it. The only truly reliable way to resolve it seems to be with the user closing and re-opening the browser.

**Comment by Extheoisah** [comment] 2022-11-07 10:30
Resolved with new POS redesign

**Closed by Extheoisah** 2022-11-07 10:30 UTC
Labels: bug
