### ISSUE TITLE
Numbers getting cut off on small screen/old phone iOS iphone 6s

### ISSUE THREAD

**Issue by agbegin** [GaloyMoney/galoy-pay#508] opened 2023-06-02 16:03 UTC
No accessibility/text features on... mobile safari is cutting off numbers. Also the dropdown looks weird, not sure if there is an easy way to change it so it's not half light grey, half dark grey.

![IMG_0281](https://github.com/GaloyMoney/galoy-pay/assets/90297599/7a94e711-6fc5-42d8-b0b6-cdcb4a70c9cf)

**Comment by UncleSamtoshi** [comment] 2023-06-07 17:21
Closing this because I was unable to reproduce it.

**Closed by UncleSamtoshi** 2023-06-07 17:21 UTC
